In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("bank-full.csv")

In [3]:
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome Target  
0  unknown    5   may       261         1     -1         0  unknown     no  
1  unknown    5   may       151         1     -1         0  unknown     no  
2  unknown    5   may        76         1     -1         0  unknown     no  
3  unknown    5   may        92         1     -1         0  unknown     no  
4  unknown    5   may       198         1     -1         0  unknown     no

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le= LabelEncoder()

In [6]:
df['job']=le.fit_transform(df['job'])
df['marital']=le.fit_transform(df['marital'])
df['education']=le.fit_transform(df['education'])
df['default']=le.fit_transform(df['default'])
df['housing']=le.fit_transform(df['housing'])
df['loan']=le.fit_transform(df['loan'])
df['contact']=le.fit_transform(df['contact'])
df['month']=le.fit_transform(df['month'])
df['poutcome']=le.fit_transform(df['poutcome'])
df['Target']=le.fit_transform(df['Target'])

In [7]:
df

age  job  marital  education  default  balance  housing  loan  contact  \
0       58    4        1          2        0     2143        1     0        2   
1       44    9        2          1        0       29        1     0        2   
2       33    2        1          1        0        2        1     1        2   
3       47    1        1          3        0     1506        1     0        2   
4       33   11        2          3        0        1        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
45206   51    9        1          2        0      825        0     0        0   
45207   71    5        0          0        0     1729        0     0        0   
45208   72    5        1          1        0     5715        0     0        0   
45209   57    1        1          1        0      668        0     0        1   
45210   37    2        1          1        0     2971        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  Target  
0        5      8       261         1     -1         0         3       0  
1        5      8       151         1     -1         0         3       0  
2        5      8        76         1     -1         0         3       0  
3        5      8        92         1     -1         0         3       0  
4        5      8       198         1     -1         0         3       0  
...    ...    ...       ...       ...    ...       ...       ...     ...  
45206   17      9       977         3     -1         0         3       1  
45207   17      9       456         2     -1         0         3       1  
45208   17      9      1127         5    184         3         2       1  
45209   17      9       508         4     -1         0         3       0  
45210   17      9       361         2    188        11         1       0  

[45211 rows x 17 columns]

In [8]:
x=df.drop('Target',axis=1)
y=df[['Target']]

In [9]:
x

age  job  marital  education  default  balance  housing  loan  contact  \
0       58    4        1          2        0     2143        1     0        2   
1       44    9        2          1        0       29        1     0        2   
2       33    2        1          1        0        2        1     1        2   
3       47    1        1          3        0     1506        1     0        2   
4       33   11        2          3        0        1        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
45206   51    9        1          2        0      825        0     0        0   
45207   71    5        0          0        0     1729        0     0        0   
45208   72    5        1          1        0     5715        0     0        0   
45209   57    1        1          1        0      668        0     0        1   
45210   37    2        1          1        0     2971        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  
0        5      8       261         1     -1         0         3  
1        5      8       151         1     -1         0         3  
2        5      8        76         1     -1         0         3  
3        5      8        92         1     -1         0         3  
4        5      8       198         1     -1         0         3  
...    ...    ...       ...       ...    ...       ...       ...  
45206   17      9       977         3     -1         0         3  
45207   17      9       456         2     -1         0         3  
45208   17      9      1127         5    184         3         2  
45209   17      9       508         4     -1         0         3  
45210   17      9       361         2    188        11         1  

[45211 rows x 16 columns]

In [10]:
# Scaling of the input data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)
scaled_feature=scaler.transform(x)
scaled_feature


array([[ 1.60696496, -0.10381968, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       [ 0.28852927,  1.42400783,  1.3683719 , ..., -0.41145311,
        -0.25194037,  0.44489814],
       [-0.74738448, -0.71495069, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       ...,
       [ 2.92540065,  0.20174582, -0.27576178, ...,  1.43618859,
         1.05047333, -0.56617504],
       [ 1.51279098, -1.02051619, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       [-0.37068857, -0.71495069, -0.27576178, ...,  1.4761376 ,
         4.52357654, -1.57724822]])

In [11]:
df_scaled = pd.DataFrame(data = scaled_feature,columns = x.columns)
x=df_scaled
x

age       job   marital  education  default   balance   housing  \
0      1.606965 -0.103820 -0.275762   1.036362 -0.13549  0.256419  0.893915   
1      0.288529  1.424008  1.368372  -0.300556 -0.13549 -0.437895  0.893915   
2     -0.747384 -0.714951 -0.275762  -0.300556 -0.13549 -0.446762  0.893915   
3      0.571051 -1.020516 -0.275762   2.373280 -0.13549  0.047205  0.893915   
4     -0.747384  2.035139  1.368372   2.373280 -0.13549 -0.447091 -1.118674   
...         ...       ...       ...        ...      ...       ...       ...   
45206  0.947747  1.424008 -0.275762   1.036362 -0.13549 -0.176460 -1.118674   
45207  2.831227  0.201746 -1.919895  -1.637474 -0.13549  0.120447 -1.118674   
45208  2.925401  0.201746 -0.275762  -0.300556 -0.13549  1.429593 -1.118674   
45209  1.512791 -1.020516 -0.275762  -0.300556 -0.13549 -0.228024 -1.118674   
45210 -0.370689 -0.714951 -0.275762  -0.300556 -0.13549  0.528364 -1.118674   

           loan   contact       day     month  duration  campaign     pdays  \
0     -0.436803  1.514306 -1.298476  0.823773  0.011016 -0.569351 -0.411453   
1     -0.436803  1.514306 -1.298476  0.823773 -0.416127 -0.569351 -0.411453   
2      2.289359  1.514306 -1.298476  0.823773 -0.707361 -0.569351 -0.411453   
3     -0.436803  1.514306 -1.298476  0.823773 -0.645231 -0.569351 -0.411453   
4     -0.436803  1.514306 -1.298476  0.823773 -0.233620 -0.569351 -0.411453   
...         ...       ...       ...       ...       ...       ...       ...   
45206 -0.436803 -0.713012  0.143418  1.156344  2.791329  0.076230 -0.411453   
45207 -0.436803 -0.713012  0.143418  1.156344  0.768224 -0.246560 -0.411453   
45208 -0.436803 -0.713012  0.143418  1.156344  3.373797  0.721811  1.436189   
45209 -0.436803  0.400647  0.143418  1.156344  0.970146  0.399020 -0.411453   
45210 -0.436803 -0.713012  0.143418  1.156344  0.399328 -0.246560  1.476138   

       previous  poutcome  
0     -0.251940  0.444898  
1     -0.251940  0.444898  
2     -0.251940  0.444898  
3     -0.251940  0.444898  
4     -0.251940  0.444898  
...         ...       ...  
45206 -0.251940  0.444898  
45207 -0.251940  0.444898  
45208  1.050473 -0.566175  
45209 -0.251940  0.444898  
45210  4.523577 -1.577248  

[45211 rows x 16 columns]

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score 

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=50)

In [14]:
# Logistic Regression & its cross validation
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr_pred=lr.predict(x_test)
accuracy_score(y_test,lr_pred)

C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.893394278973754

In [15]:
#Cross validation
score_lr=cross_val_score(lr,x,y,cv=10)
score_lr

C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

array([0.89296771, 0.91749613, 0.91395709, 0.87923026, 0.88984738,
       0.88033621, 0.86020792, 0.86861314, 0.87082504, 0.85954435])

In [16]:
#Decision Tree & its cross validation
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt_pred=dt.predict(x_test)
accuracy_score(y_test,dt_pred)

0.877690946623415

In [17]:
score_dt=cross_val_score(dt,x,y,cv=10)
score_dt

array([0.88014153, 0.61579297, 0.65737669, 0.67883212, 0.74850697,
       0.690334  , 0.5885866 , 0.40455651, 0.60252157, 0.48330015])

In [18]:
# KNN and its cross validation
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
knn_pred=knn.predict(x_test)
accuracy_score(y_test,knn_pred)

C:\Users\colourfulm\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.8939840754939545

In [19]:
score_knn=cross_val_score(knn,x,y,cv=10)
score_knn

C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarnin

array([0.88743919, 0.83720416, 0.87945145, 0.83078965, 0.83543464,
       0.81508516, 0.85091794, 0.78898474, 0.82039372, 0.70095112])

In [20]:
# implementation stratified k fold for logistic regression
from sklearn.model_selection import StratifiedKFold

In [33]:
accuracy=[]
skf=StratifiedKFold(n_splits=10,random_state=200)
skf.get_n_splits(x,y)  

10

In [34]:
for train_index,test_index in skf.split(x,y):
    x1_train,x1_test=x.iloc[train_index],x.iloc[test_index]
    y1_train,y1_test=y.iloc[train_index],y.iloc[test_index]
    lr.fit(x1_train,y1_train)
    lr1_pred=lr.predict(x1_test)
    sc=accuracy_score(y1_test,lr1_pred)
    accuracy.append(sc)

C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\colourfulm\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

In [35]:
accuracy

[0.8929677134011499,
 0.9174961291749613,
 0.9139570891395709,
 0.8792302587923025,
 0.8898473788984738,
 0.880336208803362,
 0.8602079186020792,
 0.8686131386861314,
 0.8708250387082503,
 0.8595443485954435]

In [36]:
# implementation of decision tree through stratified k fold
accuracy1=[]
for train_index,test_index in skf.split(x,y):
    x1_train,x1_test=x.iloc[train_index],x.iloc[test_index]
    y1_train,y1_test=y.iloc[train_index],y.iloc[test_index]
    dt.fit(x1_train,y1_train)
    dt1_pred=dt.predict(x1_test)
    sc1=accuracy_score(y1_test,dt1_pred)
    accuracy1.append(sc1)

In [37]:
accuracy1

[0.8836797877045555,
 0.5925680159256802,
 0.6558283565582835,
 0.683477106834771,
 0.7454103074541031,
 0.6788321167883211,
 0.5872594558725945,
 0.4012386640123866,
 0.5834992258349923,
 0.48794514487945145]

In [38]:
# implementation of KNN through stratified k fold
accuracy2=[]
for train_index,test_index in skf.split(x,y):
    x1_train,x1_test=x.iloc[train_index],x.iloc[test_index]
    y1_train,y1_test=y.iloc[train_index],y.iloc[test_index]
    knn.fit(x1_train,y1_train)
    knn1_pred=knn.predict(x1_test)
    sc2=accuracy_score(y1_test,knn1_pred)
    accuracy2.append(sc2)

C:\Users\colourfulm\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  
C:\Users\colourfulm\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  
C:\Users\colourfulm\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  
C:\Users\colourfulm\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  
C:\Users\colourfulm\anaconda3\lib\site-packages\ipykernel_launcher.py:6:

In [39]:
accuracy2

[0.8874391862007961,
 0.8372041583720415,
 0.8794514487945145,
 0.8307896483078965,
 0.8354346383543464,
 0.8150851581508516,
 0.8509179385091794,
 0.7889847378898474,
 0.8203937182039371,
 0.7009511170095112]

In [40]:
table=[[score_lr.mean(),score_dt.mean(),score_knn.mean()]]
table.append([score_lr.std(),score_dt.std(),score_knn.std()])
table.append([np.mean(accuracy),np.mean(accuracy1),np.mean(accuracy2)])
table.append([np.std(accuracy),np.std(accuracy1),np.std(accuracy2)])
table
table1=pd.DataFrame(table,index=['K-Fold Accury_Mean','K-Fold Accury_SD','StratifiedKFold Acc_Mean','StratifiedKFold Acc_SD'])
table1.columns=['Logis Reg','Decision Tree','KNN']
table1

Logis Reg  Decision Tree       KNN
K-Fold Accury_Mean         0.883303       0.634995  0.824665
K-Fold Accury_SD           0.019339       0.125760  0.049629
StratifiedKFold Acc_Mean   0.883303       0.629974  0.824665
StratifiedKFold Acc_SD     0.019339       0.127077  0.049629